### ISSUE TITLE
Roadmap to Shared Components API Refresh.

### ISSUE THREAD

**Issue by Aubron** [Bandwidth/shared-components#192]
Not willing to tie this to a version number, since there's no telling the amount of time this effort will take, and right now we're pushing breaking changes somewhat regularly.

With the overall goal of firming up the API, decreasing the number of breaking changes we push moving forward, and making `shared-components` more of a generally usable library moving forward across products, we're embarking upon an effort to do a full api Refresh.

### Goals

- [ ] [Create a guiding methodology for api design and component reusability](https://github.com/Bandwidth/shared-components/issues/191)
- [ ] [Determine our theming solution, how extensive it is, and assemble the schema for default theme(s). ](https://github.com/Bandwidth/shared-components/issues/190)
- [ ] Turn that into assets like a pull request, contributing, and issue template.
- [ ] Review existing components for adherence to the above principals, as well as other useful changes, and bring those components up to spec.
